/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'askuck' at '2/7/16 4:16 PM' with Gradle 2.10
 *
 * @author askuck, @date 2/7/16 4:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
